py37:
  image: python:3.7-slim
  script:
    - python3.7 -m pip install tox
    - tox -r -e py37

style:
  image: python:3.7-slim
  script:
    - python3.7 -m pip install tox
    - tox -r -e style

mypy:
  image: python:3.7-slim
  script:
    - python3.7 -m pip install tox
    - tox -r -e mypy

docker:
  image: docker:git
  services:
    - docker:dind
  script:
    - timeout 5m -sKILL docker build .
  retry: 1
