version: "3"
services:
  web:
    build: .
    command: /code/start-web.sh
    environment:
      VIRTUAL_HOST: cfp.pygotham.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: cfp.pygotham.org
      # TODO: this should really go to a group or ailias
      LETSENCRYPT_EMAIL: jon@pygotham.org
    links:
      - db
    volumes:
      - ./yakbak.toml-prod:/code/yakbak.toml
    restart: on-failure

  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      VIRTUAL_HOST: stats.cfp.pygotham.org
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: stats.cfp.pygotham.org
      # TODO: this should really go to a group or ailias
      LETSENCRYPT_EMAIL: jon@pygotham.org
    links:
      - db
    volumes:
      - grafana-data:/var/lib/grafana
    restart: on-failure

  db:
    image: "postgres:10-alpine"
    volumes:
      - /home/pygotham/docker-volumes/db_data:/var/lib/postgresql/data
    env_file:
      # Don't store database secrets in source control
      - ./database-secrets.env
    restart: on-failure

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d


  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: on-failure
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d

volumes:
  certs:
  conf:
  dhparam:
  grafana-data:
  html:
  vhost:

networks:
  default:
    external:
      name: nginx-proxy
